### ISSUE TITLE
Timestamp parameter as double truncates trailing zeroes

### ISSUE THREAD

**Issue by bjorndavis** [JamesMarcogliese/slack-api-csharp#1]
I've verified this using the test for [reactions.get](https://api.slack.com/methods/reactions.get/test):
1. Using a timestamp that ends with trailing zeroes (e.g. 1549470028.002800) works fine and gets related reactions.
2. Removing the trailing zeroes (e.g. 1549470028.0028) results in the following response:
```
{
    "ok": false,
    "error": "message_not_found"
}
```

When passing the `timestamp` parameter as a double to a method in slack-api-csharp, for instance:
```
double ts = 1549470028.002800;
var resp = await slackWebAPI.Reactions.GetWithHttpMessagesAsync(token: token, channel: "the-channel", timestamp: ts);
```
you can see when debugging that the trailing zeroes in `ts`  are truncated and the method returns the same `message_not_found` response as above.

**Comment by bjorndavis** [comment]
Would it be possible to modify the `timestamp` parameter to be a string instead?

**Comment by JamesMarcogliese** [comment]
Hi @bjorndavis , 

Thanks for raising this! I did a bit of digging, turns out [Slack uses two type of timestamps](https://github.com/slackhq/slack-api-docs/issues/7) depending on the object getting exchanged. Most of them are considered int/long, but message timestamps are strings. (Naming between the two should be changed for clarity in my opinion). I'll make a change later on today. If you spot anything else, please let me know, the classes might be littered with these.

**Comment by JamesMarcogliese** [comment]
Won't get a chance today, I will get to it tomorrow. I'll try to remove all the doubles I see and push this and the SlackAction addition to NuGet.

**Comment by bjorndavis** [comment]
Thanks for taking a look!  I'm excited to get back to using it once the changes have been made.

**Comment by JamesMarcogliese** [comment]
I've made the changes. Replaced all the instances of the auto-generated double type with whatever was specified in the documentation; most were to string, some were to int. I've updated the repo and pushed the package to NuGet.

**Comment by bjorndavis** [comment]
Thanks for the quick update!
